
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpqgbgtqkuxuxpodpjri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcWdiZ3Rxa3V4dXhwb2RwanJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTkxMTAsImV4cCI6MjA2MzM5NTExMH0.wnYubv0gbXSw_af6HCaKcqFYYCD4KabnduuQHJlWLok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
